### ISSUE TITLE
Broken library header

### ISSUE THREAD

**Issue by tarsius** [DerBeutlin/ros.el#15]
Frodo,

It appears you are generating the library header and that the tool failed for 63d46cefa8552b59556dcb4af0849253dc501ee9.

```elisp
;; Keywords: Symbol’s value as variable is void: finder-known-keywords
```

More importantly the summary and commentary are now simply "Description". Please fix these issues and maybe make your tool a bit more robust. :grin: 

(I just saw this by chance, because of https://github.com/melpa/melpa/pull/7934.)

**Comment by DerBeutlin** [comment]
Thanks for catching that :)
